import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "MoneyFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="bg-gray-100 w-full">
            <SidebarTrigger className="cursor-pointer md:hidden" />
            <div className="mx-4 md:mt-4">{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
